### ISSUE TITLE
Translate UASupport to all European languages

### ISSUE THREAD

**Issue by overby-me** [burnpiro/uasupport#1]
| No Translators | Work in Progress | Done |
|-|-|-|
| ❌ | 🚧 | :heavy_check_mark:  |

| Status | Language | Translators / Coordinators | PR | Merged |
|-|-|-|-|-|
| :heavy_check_mark: | 🇧🇬 Bulgarian | Mikołaj Kniejski (Coordinator) | #10 | :heavy_check_mark: |
| :heavy_check_mark: | 🇭🇷 Croatian | Niclas Overby (Coordinator) | #17 |
| :heavy_check_mark: | 🇨🇿 Czech | Vojtěch Jindra | #12  | :heavy_check_mark: |
| :heavy_check_mark: | 🇩🇰 Danish | Mikkel Kristensen | #2 | :heavy_check_mark: |
| :heavy_check_mark: | 🇳🇱 Dutch | Raphael Dürscheid (Coordinator) | #4 | :heavy_check_mark: |
| :heavy_check_mark: | 🇬🇧 English | Kemal Erdem | | :heavy_check_mark: |
| :heavy_check_mark:  | 🇪🇪 Estonian | Mikołaj Kniejski (Coordinator) | #19  | |
| :heavy_check_mark: | 🇫🇮 Finnish | Niclas Overby (Coordinator) | #18 | |
| :heavy_check_mark: | 🇫🇷 French | Stefan Alexandru | #25 | |
| :heavy_check_mark: | 🇩🇪 German | Raphael Dürscheid | #5 | :heavy_check_mark: |
| :heavy_check_mark: | 🇬🇷 Greek | Γεωργία Αναγνωστάκη | #27 | |
| :heavy_check_mark: | 🇭🇺 Hungarian | Mikołaj Kniejski (Coordinator) | #23 | |
| :heavy_check_mark: | 🇮🇹 Italian | Kelly Antonini | #7 |  :heavy_check_mark: |
| :heavy_check_mark: | 🇱🇻 Latvian | Katrīna Spure | #21  | |
| 🚧 | 🇱🇹 Lithuanian | Guilherme Mateus (Coordinator) | | |
| :heavy_check_mark: | 🇲🇹 Maltese | Michaela Spiteri | #11 | :heavy_check_mark: |
| :heavy_check_mark: | 🇳🇴 Norwegian | Martin Svangtun| #14 | :heavy_check_mark: |
| :heavy_check_mark: | 🇵🇱 Polish | Kemal Erdem | | :heavy_check_mark: |
| :heavy_check_mark: | 🇵🇹 Portuguese | Guilherme Mateus | #8 | :heavy_check_mark: |
| :heavy_check_mark: | 🇷🇴 Romanian | Stefan Alexandru | #24 | |
| :heavy_check_mark: | 🇷🇺 Russian | Kemal Erdem | | :heavy_check_mark: |
| :heavy_check_mark: | 🇸🇰 Slovak | Niclas Overby (Coordinator) |  #3 | :heavy_check_mark: |
| :heavy_check_mark: | 🇸🇮 Slovenian | Niclas Overby (Coordinator) | #20 | |
| :heavy_check_mark: | 🇪🇸 Spanish | Guilherme Mateus | #26 | |
| :heavy_check_mark: | 🇸🇪 Swedish | Mikołaj Kniejski (Coordinator) | #13 | :heavy_check_mark: |
| :heavy_check_mark: | 🇺🇦 Ukrainian | Kemal Erdem | | :heavy_check_mark: |

**Comment by compiaffe** [comment]
@noverby Dutch MR: https://github.com/burnpiro/uasupport/pull/4 and German MR https://github.com/burnpiro/uasupport/pull/5

Italian will arrive tomorrow.

**Comment by compiaffe** [comment]
Romanian will come via Mikołaj

**Comment by burnpiro** [comment]
I've creates a separate feature branch [feature/translations](https://github.com/burnpiro/uasupport/tree/feature/translations) with all menu options and settings required for translations. That includes a new menu
![image](https://user-images.githubusercontent.com/3284639/158277727-a70a7f0f-94a7-4a9e-8c0e-80618e4eb75b.png)

Ukrainian, Russian and English are staying at the top of the list, the rest is alphabetical by country
