### ISSUE TITLE
Glitch in language selector with previous login session

### ISSUE THREAD

**Issue by overby-me** [burnpiro/uasupport#16]
There is a visual glitch, if you have logged-in previously.

It does not show up in a whole new session.

![image](https://user-images.githubusercontent.com/2422942/158573293-d34963c2-bb9f-4f23-89c3-17fac3072984.png)

**Comment by burnpiro** [comment]
that is caused by the cache reloading. All our icons are cached and they had to be moved to a separate location in the latest build.  After the cache is reloaded it shouldn't be a problem anymore.

**Comment by overby-me** [comment]
Ok let's close it then
